#!/bin/bash
#PBS -P em5
#PBS -q normal
#PBS -l storage=scratch/em5+gdata/ey6
#PBS -l walltime=22:00:00
#PBS -l mem=160GB
#PBS -l jobfs=500MB
#PBS -l ncpus=48
#PBS -l wd

/scratch/em5/jj4710/BOLT/bolt \
    --bed=/g/data/ey6/UKBB_GeneticData/bed_files/ukb_cal_chr{1:22}_v2.bed \
    --bim=/g/data/ey6/UKBB_GeneticData/bim_files/ukb_snp_chr{1:22}_v2.bim \
    --fam=/scratch/em5/jj4710/UKB/fam_files/mod_ukb58534_cal_chr1_v2_s488264.fam \
    --phenoFile=/scratch/em5/jj4710/UKB/pheno_covar_wb_nojob \
    --phenoCol=zwb_nojob \
    --covarFile=/scratch/em5/jj4710/UKB/pheno_covar_wb_nojob \
    --covarCol=sex \
    --covarCol=genotype_array \
    --qCovarCol=age \
    --qCovarCol=age_sqrt \
    --qCovarCol=pc{1:20} \
    --lmm \
    --LDscoresFile=/scratch/em5/jj4710/BOLT/tables/LDSCORE.1000G_EUR.tab.gz \
    --geneticMapFile=/scratch/em5/jj4710/BOLT/tables/genetic_map_hg19_withX.txt.gz \
    --lmmForceNonInf \
    --numThreads=48 \
    --statsFile=wbNOJOB_caucasian.stats.gz \
    --bgenFile=/g/data/ey6/UKBB_GeneticData/bgen_files/ukb_imp_chr{1:22}_v3.bgen \
    --bgenMinMAF=0.01 \
    --bgenMinINFO=0.3 \
    --sampleFile=/scratch/em5/jj4710/UKB/sam_files/ukb58534_imp_chr2_v3_s487296.sample\
    --statsFileBgenSnps=wbNOJOB_caucasian.bgen.stats.gz \
    --remove=/scratch/em5/jj4710/UKB/fam_butnot_sam \
    --remove=/scratch/em5/jj4710/UKB/remove \
    --verboseStats
